// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: main.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GRPCClient {
  public static partial class MainService
  {
    static readonly string __ServiceName = "main.MainService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GRPCClient.HandshakePost> __Marshaller_main_HandshakePost = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GRPCClient.HandshakePost.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GRPCClient.HandshakeGet> __Marshaller_main_HandshakeGet = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GRPCClient.HandshakeGet.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GRPCClient.NHandshakePost> __Marshaller_main_NHandshakePost = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GRPCClient.NHandshakePost.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GRPCClient.NHandshakeGet> __Marshaller_main_NHandshakeGet = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GRPCClient.NHandshakeGet.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GRPCClient.PingPost> __Marshaller_main_PingPost = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GRPCClient.PingPost.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GRPCClient.PingGet> __Marshaller_main_PingGet = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GRPCClient.PingGet.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GRPCClient.NetObjUpdate> __Marshaller_main_NetObjUpdate = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GRPCClient.NetObjUpdate.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GRPCClient.EmptyMsg> __Marshaller_main_EmptyMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GRPCClient.EmptyMsg.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GRPCClient.HandshakePost, global::GRPCClient.HandshakeGet> __Method_Handshake = new grpc::Method<global::GRPCClient.HandshakePost, global::GRPCClient.HandshakeGet>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Handshake",
        __Marshaller_main_HandshakePost,
        __Marshaller_main_HandshakeGet);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GRPCClient.NHandshakePost, global::GRPCClient.NHandshakeGet> __Method_NetcodeHandshake = new grpc::Method<global::GRPCClient.NHandshakePost, global::GRPCClient.NHandshakeGet>(
        grpc::MethodType.Unary,
        __ServiceName,
        "NetcodeHandshake",
        __Marshaller_main_NHandshakePost,
        __Marshaller_main_NHandshakeGet);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GRPCClient.PingPost, global::GRPCClient.PingGet> __Method_Ping = new grpc::Method<global::GRPCClient.PingPost, global::GRPCClient.PingGet>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Ping",
        __Marshaller_main_PingPost,
        __Marshaller_main_PingGet);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GRPCClient.NetObjUpdate, global::GRPCClient.EmptyMsg> __Method_SrvNetObjUpdate = new grpc::Method<global::GRPCClient.NetObjUpdate, global::GRPCClient.EmptyMsg>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "SrvNetObjUpdate",
        __Marshaller_main_NetObjUpdate,
        __Marshaller_main_EmptyMsg);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GRPCClient.EmptyMsg, global::GRPCClient.NetObjUpdate> __Method_CliNetObjUpdate = new grpc::Method<global::GRPCClient.EmptyMsg, global::GRPCClient.NetObjUpdate>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "CliNetObjUpdate",
        __Marshaller_main_EmptyMsg,
        __Marshaller_main_NetObjUpdate);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GRPCClient.MainReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MainService</summary>
    [grpc::BindServiceMethod(typeof(MainService), "BindService")]
    public abstract partial class MainServiceBase
    {
      /// <summary>
      ///Establish first connection with client
      ///Sync all NetworkBehaviour + SyncVars
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GRPCClient.HandshakeGet> Handshake(global::GRPCClient.HandshakePost request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GRPCClient.NHandshakeGet> NetcodeHandshake(global::GRPCClient.NHandshakePost request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Ping stream checks regularly for client connections 
      ///(Used to disconnect safely from game if no response)
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task Ping(grpc::IAsyncStreamReader<global::GRPCClient.PingPost> requestStream, grpc::IServerStreamWriter<global::GRPCClient.PingGet> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GRPCClient.EmptyMsg> SrvNetObjUpdate(grpc::IAsyncStreamReader<global::GRPCClient.NetObjUpdate> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task CliNetObjUpdate(global::GRPCClient.EmptyMsg request, grpc::IServerStreamWriter<global::GRPCClient.NetObjUpdate> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MainService</summary>
    public partial class MainServiceClient : grpc::ClientBase<MainServiceClient>
    {
      /// <summary>Creates a new client for MainService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MainServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MainService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MainServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MainServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MainServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///Establish first connection with client
      ///Sync all NetworkBehaviour + SyncVars
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GRPCClient.HandshakeGet Handshake(global::GRPCClient.HandshakePost request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Handshake(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Establish first connection with client
      ///Sync all NetworkBehaviour + SyncVars
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GRPCClient.HandshakeGet Handshake(global::GRPCClient.HandshakePost request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Handshake, null, options, request);
      }
      /// <summary>
      ///Establish first connection with client
      ///Sync all NetworkBehaviour + SyncVars
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GRPCClient.HandshakeGet> HandshakeAsync(global::GRPCClient.HandshakePost request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HandshakeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Establish first connection with client
      ///Sync all NetworkBehaviour + SyncVars
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GRPCClient.HandshakeGet> HandshakeAsync(global::GRPCClient.HandshakePost request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Handshake, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GRPCClient.NHandshakeGet NetcodeHandshake(global::GRPCClient.NHandshakePost request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return NetcodeHandshake(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GRPCClient.NHandshakeGet NetcodeHandshake(global::GRPCClient.NHandshakePost request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_NetcodeHandshake, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GRPCClient.NHandshakeGet> NetcodeHandshakeAsync(global::GRPCClient.NHandshakePost request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return NetcodeHandshakeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GRPCClient.NHandshakeGet> NetcodeHandshakeAsync(global::GRPCClient.NHandshakePost request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_NetcodeHandshake, null, options, request);
      }
      /// <summary>
      ///Ping stream checks regularly for client connections 
      ///(Used to disconnect safely from game if no response)
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::GRPCClient.PingPost, global::GRPCClient.PingGet> Ping(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Ping stream checks regularly for client connections 
      ///(Used to disconnect safely from game if no response)
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::GRPCClient.PingPost, global::GRPCClient.PingGet> Ping(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Ping, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::GRPCClient.NetObjUpdate, global::GRPCClient.EmptyMsg> SrvNetObjUpdate(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SrvNetObjUpdate(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::GRPCClient.NetObjUpdate, global::GRPCClient.EmptyMsg> SrvNetObjUpdate(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_SrvNetObjUpdate, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::GRPCClient.NetObjUpdate> CliNetObjUpdate(global::GRPCClient.EmptyMsg request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CliNetObjUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::GRPCClient.NetObjUpdate> CliNetObjUpdate(global::GRPCClient.EmptyMsg request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_CliNetObjUpdate, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MainServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MainServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MainServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Handshake, serviceImpl.Handshake)
          .AddMethod(__Method_NetcodeHandshake, serviceImpl.NetcodeHandshake)
          .AddMethod(__Method_Ping, serviceImpl.Ping)
          .AddMethod(__Method_SrvNetObjUpdate, serviceImpl.SrvNetObjUpdate)
          .AddMethod(__Method_CliNetObjUpdate, serviceImpl.CliNetObjUpdate).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MainServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Handshake, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GRPCClient.HandshakePost, global::GRPCClient.HandshakeGet>(serviceImpl.Handshake));
      serviceBinder.AddMethod(__Method_NetcodeHandshake, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GRPCClient.NHandshakePost, global::GRPCClient.NHandshakeGet>(serviceImpl.NetcodeHandshake));
      serviceBinder.AddMethod(__Method_Ping, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::GRPCClient.PingPost, global::GRPCClient.PingGet>(serviceImpl.Ping));
      serviceBinder.AddMethod(__Method_SrvNetObjUpdate, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::GRPCClient.NetObjUpdate, global::GRPCClient.EmptyMsg>(serviceImpl.SrvNetObjUpdate));
      serviceBinder.AddMethod(__Method_CliNetObjUpdate, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::GRPCClient.EmptyMsg, global::GRPCClient.NetObjUpdate>(serviceImpl.CliNetObjUpdate));
    }

  }
}
#endregion
